import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className='d-flex justify-content-center gap-3'>
          <Link href="/" className='btn btn-info' replace>Home</Link>
          <Link href="/login" className='btn btn-info' replace>Sign In</Link>
          <Link href="/dashboard" className='btn btn-info' replace>Dashboard</Link>
        </div>

        {children}
        
        </body>
    </html>
  )
}
